server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: 1ic6cvkuk1j3qekuephv925odg
            scope: openid, email, phone
            redirect-uri: "{baseUrl}/siteB"
            client-authentication-method: post
            authorization-grant-type: authorization_code
            provider: cognito
        provider:
          cognito:
            authorization-uri: https://web02.auth.us-east-1.amazoncognito.com/oauth2/authorize
            token-uri: https://web02.auth.us-east-1.amazoncognito.com/oauth2/token
            user-info-uri: https://web02.auth.us-east-1.amazoncognito.com/oauth2/userInfo
            user-name-attribute: sub
            jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_kPfzTh4dA/.well-known/jwks.json
            issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_kPfzTh4dA